### ISSUE TITLE
@blacklisted long url error

### ISSUE THREAD

**Issue by SupremeSkriptKiddie** [yogeshwaran01/maskurl#1]
I've used this tool in the past with no problems so when i tried using it on my parrotos box i was surprised when it said all of my tests are black listed
![maskissue1](https://user-images.githubusercontent.com/68531401/106394316-f7c4ba80-63f3-11eb-902a-581b0a8f2dff.png)
![maskissue2](https://user-images.githubusercontent.com/68531401/106394318-fbf0d800-63f3-11eb-948b-677b614b6360.png)
![maskissue3](https://user-images.githubusercontent.com/68531401/106394321-fd220500-63f3-11eb-91d1-3ba5b60032f2.png)

**Comment by n1s4t** [comment]
You can use mask phish

**Comment by yogeshwaran01** [comment]
@guyfawkes69  Thank you for indicating this issue. Now, this issue was completely fixed. Just update maskurl by `git pull`
